language: python
python:
    - "2.7.11"
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script: "nosetests test/unit_tests --with-coverage --cover-package passzero"
after_success:
    - coveralls
