sudo: false
dist: focal
language: python
python:
    - "3.8"
matrix:
    include:
        - python: "3.8.7"
          dist: xenial
          sudo: true
install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements-dev.txt"
    - "pip install coveralls"
env:
    - DATABASE_URL="sqlite:///passzero.db" MAILGUN_API_KEY="xxxxxxxxxxxxxxxxxxxxxxxx"
script: "PYTHONPATH=. pytest tests/unit_tests --cov=passzero"
after_success:
    - coveralls
