language: python
python:
    - "2.7.11"
install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements-dev.txt"
    - "pip install coveralls"
script: "PYTHONPATH=. py.test tests/unit_tests --cov=passzero"
after_success:
    - coveralls
