CREATE TABLE IF NOT EXISTS users
    (id INTEGER PRIMARY KEY, email VARCHAR UNIQUE NOT NULL,
     password VARCHAR NOT NULL, salt CHAR(32) NOT NULL, active BOOLEAN DEFAULT FALSE);

CREATE TABLE IF NOT EXISTS auth_tokens
    (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, token CHAR(32) NOT NULL);

CREATE TABLE IF NOT EXISTS entries
    (id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL, account VARCHAR UNIQUE NOT NULL,
    username VARCHAR NOT NULL, password VARCHAR NOT NULL,
    padding VARCHAR NOT NULL);
