CREATE TABLE IF NOT EXISTS users
    (id SERIAL PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    salt CHAR(32) NOT NULL,
    active BOOLEAN DEFAULT FALSE,
    last_login TIMESTAMP NOT NULL DEFAULT NOW());

CREATE TABLE IF NOT EXISTS auth_tokens
    (id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    token CHAR(32) NOT NULL,
    issue_time TIMESTAMP NOT NULL DEFAULT NOW());

CREATE TABLE IF NOT EXISTS entries
    (id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    account VARCHAR NOT NULL,
    username VARCHAR NOT NULL, password VARCHAR NOT NULL,
    padding VARCHAR NOT NULL,
    extra TEXT);
