version: "3.9"
services:
  passzero:
    build: .
    image: 'passzero:latest'
    container_name: passzero
    environment:
      # NOTE: this connection string must match the credentials below
      # this is for accessing the postgres DB on the host
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal/passzero
      # NOTE: this is fake (obviously)
      - SENDGRID_API_KEY=x
    ports:
      - "8000:8000"